// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Data for an IAM policy.
public struct Policy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the `Policy`, which must be unique. Format:
  /// `policies/{attachment_point}/denypolicies/{policy_id}`
  ///
  ///
  /// The attachment point is identified by its URL-encoded full resource name,
  /// which means that the forward-slash character, `/`, must be written as
  /// `%2F`. For example,
  /// `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
  ///
  /// For organizations and folders, use the numeric ID in the full resource
  /// name. For projects, requests can use the alphanumeric or the numeric ID.
  /// Responses always contain the numeric ID.
  public var name: Swift.String = Swift.String()

  /// Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
  /// `Policy` is created.
  public var uid: Swift.String = Swift.String()

  /// Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
  public var kind: Swift.String = Swift.String()

  /// A user-specified description of the `Policy`. This value can be up to 63
  /// characters.
  public var displayName: Swift.String = Swift.String()

  /// A key-value map to store arbitrary metadata for the `Policy`. Keys
  /// can be up to 63 characters. Values can be up to 255 characters.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// An opaque tag that identifies the current version of the `Policy`. IAM uses
  /// this value to help manage concurrent updates, so they do not cause one
  /// update to be overwritten by another.
  ///
  /// If this field is present in a [CreatePolicy][] request, the value is
  /// ignored.
  public var etag: Swift.String = Swift.String()

  /// Output only. The time when the `Policy` was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the `Policy` was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
  public var deleteTime: GoogleCloudWKT.Timestamp? = nil

  /// A list of rules that specify the behavior of the `Policy`. All of the rules
  /// should be of the `kind` specified in the `Policy`.
  public var rules: [PolicyRule] = []

  /// Immutable. Specifies that this policy is managed by an authority and can only be
  /// modified by that authority. Usage is restricted.
  public var managingAuthority: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Policy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Policy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let kind = CodingKeys(stringValue: "kind")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let etag = CodingKeys(stringValue: "etag")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let rules = CodingKeys(stringValue: "rules")
    static let managingAuthority = CodingKeys(stringValue: "managingAuthority")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "kind",
      "displayName",
      "annotations",
      "etag",
      "createTime",
      "updateTime",
      "deleteTime",
      "rules",
      "managingAuthority",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
      self.kind = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent([PolicyRule].self, forKey: .rules) {
      self.rules = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .managingAuthority) {
      self.managingAuthority = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.kind, forKey: .kind)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.etag, forKey: .etag)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.rules, forKey: .rules)
    try container.encode(self.managingAuthority, forKey: .managingAuthority)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.v2.Policy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
