// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// An interface for managing Identity and Access Management (IAM) policies.
///
/// @Snippet(path: "PoliciesQuickstart")
public final class PoliciesClient: Clients.PoliciesProtocol, Sendable {
  let inner: any Clients.PoliciesStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `PoliciesClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.PoliciesStub = try Clients.PoliciesTransport(options)
    inner = Clients.PoliciesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.PoliciesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Retrieves the policies of the specified kind that are attached to a
  /// resource.
  ///
  /// The response lists only policy metadata. In particular, policy rules are
  /// omitted.
  ///
  /// @Snippet(path: "Policies_ListPolicies")
  public func listPolicies(
    request: ListPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV2.ListPoliciesResponse {
    try await self.inner.listPolicies(request: request, options: options)
  }

  /// Gets a policy.
  ///
  /// @Snippet(path: "Policies_GetPolicy")
  public func getPolicy(
    request: GetPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV2.Policy {
    try await self.inner.getPolicy(request: request, options: options)
  }

  /// Creates a policy.
  ///
  /// @Snippet(path: "Policies_CreatePolicy")
  public func createPolicy(
    request: CreatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createPolicy(request: request, options: options)
  }

  /// Creates a policy.
  ///
  /// @Snippet(path: "Policies_CreatePolicy")
  public func createPolicy(
    withPolling: CreatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      return try op._extractStatus(Policy.self)
    }
    let rawOp = try await self.createPolicy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the specified policy.
  ///
  /// You can update only the rules and the display name for the policy.
  ///
  /// To update a policy, you should use a read-modify-write loop:
  ///
  /// 1. Use [GetPolicy][google.iam.v2.Policies.GetPolicy] to read the current version of the policy.
  /// 2. Modify the policy as needed.
  /// 3. Use `UpdatePolicy` to write the updated policy.
  ///
  /// This pattern helps prevent conflicts between concurrent updates.
  ///
  /// [google.iam.v2.Policies.GetPolicy]: <doc:PoliciesClient/getPolicy(request:options:)>
  ///
  /// @Snippet(path: "Policies_UpdatePolicy")
  public func updatePolicy(
    request: UpdatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updatePolicy(request: request, options: options)
  }

  /// Updates the specified policy.
  ///
  /// You can update only the rules and the display name for the policy.
  ///
  /// To update a policy, you should use a read-modify-write loop:
  ///
  /// 1. Use [GetPolicy][google.iam.v2.Policies.GetPolicy] to read the current version of the policy.
  /// 2. Modify the policy as needed.
  /// 3. Use `UpdatePolicy` to write the updated policy.
  ///
  /// This pattern helps prevent conflicts between concurrent updates.
  ///
  /// [google.iam.v2.Policies.GetPolicy]: <doc:PoliciesClient/getPolicy(request:options:)>
  ///
  /// @Snippet(path: "Policies_UpdatePolicy")
  public func updatePolicy(
    withPolling: UpdatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      return try op._extractStatus(Policy.self)
    }
    let rawOp = try await self.updatePolicy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a policy. This action is permanent.
  ///
  /// @Snippet(path: "Policies_DeletePolicy")
  public func deletePolicy(
    request: DeletePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deletePolicy(request: request, options: options)
  }

  /// Deletes a policy. This action is permanent.
  ///
  /// @Snippet(path: "Policies_DeletePolicy")
  public func deletePolicy(
    withPolling: DeletePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      return try op._extractStatus(Policy.self)
    }
    let rawOp = try await self.deletePolicy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Policies_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `PoliciesClient`.
  ///
  /// To mock `PoliciesClient` change your functions to receive
  /// `some PoliciesProtocol` or `any PoliciesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol PoliciesProtocol: Sendable {
    /// See `PoliciesClient.createPolicy`.
    func createPolicy(withPolling: CreatePolicyRequest) async throws -> any GoogleGax
      .PollableOperation<Policy>

    /// See `PoliciesClient.createPolicy`.
    func createPolicy(
      parent: Swift.String,
      policy: Policy?,
      policyId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Policy>

    /// See `PoliciesClient.updatePolicy`.
    func updatePolicy(withPolling: UpdatePolicyRequest) async throws -> any GoogleGax
      .PollableOperation<Policy>

    /// See `PoliciesClient.deletePolicy`.
    func deletePolicy(withPolling: DeletePolicyRequest) async throws -> any GoogleGax
      .PollableOperation<Policy>

    /// See `PoliciesClient.deletePolicy`.
    func deletePolicy(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Policy>

    /// See `PoliciesClient.listPolicies`.
    func listPolicies(
      request: ListPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV2.ListPoliciesResponse

    /// See `PoliciesClient.getPolicy`.
    func getPolicy(
      request: GetPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV2.Policy

    /// See `PoliciesClient.createPolicy`.
    func createPolicy(
      request: CreatePolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PoliciesClient.createPolicy`.
    func createPolicy(
      withPolling: CreatePolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Policy>

    /// See `PoliciesClient.updatePolicy`.
    func updatePolicy(
      request: UpdatePolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PoliciesClient.updatePolicy`.
    func updatePolicy(
      withPolling: UpdatePolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Policy>

    /// See `PoliciesClient.deletePolicy`.
    func deletePolicy(
      request: DeletePolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PoliciesClient.deletePolicy`.
    func deletePolicy(
      withPolling: DeletePolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Policy>
  }
}

// Default implementations
extension Clients.PoliciesProtocol {
  public func listPolicies(request: ListPoliciesRequest) async throws
    -> GoogleIAMV2.ListPoliciesResponse
  {
    try await self.listPolicies(request: request, options: .init())
  }

  public func listPolicies(
    request: ListPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV2.ListPoliciesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listPolicies(
    byItem: ListPoliciesRequest
  ) -> any AsyncSequence<Policy, Swift.Error> {
    self.listPolicies(byItem: byItem, options: .init())
  }

  /// Retrieves the policies of the specified kind that are attached to a
  /// resource.
  ///
  /// The response lists only policy metadata. In particular, policy rules are
  /// omitted.
  ///
  /// @Snippet(path: "Policies_ListPolicies")
  public func listPolicies(
    byItem: ListPoliciesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Policy, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleIAMV2.ListPoliciesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listPolicies(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPolicies(
    parent: Swift.String,
  ) -> any AsyncSequence<Policy, Swift.Error> {
    let request = ListPoliciesRequest().with {
      $0.parent = parent
    }
    return self.listPolicies(byItem: request)
  }

  public func getPolicy(request: GetPolicyRequest) async throws -> GoogleIAMV2.Policy {
    try await self.getPolicy(request: request, options: .init())
  }

  public func getPolicy(
    request: GetPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV2.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getPolicy(
    name: Swift.String,
  ) async throws -> GoogleIAMV2.Policy {
    let request = GetPolicyRequest().with {
      $0.name = name
    }
    return try await self.getPolicy(request: request)
  }

  public func createPolicy(request: CreatePolicyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createPolicy(request: request, options: .init())
  }

  public func createPolicy(
    request: CreatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createPolicy(withPolling: CreatePolicyRequest) async throws -> any GoogleGax
    .PollableOperation<Policy>
  {
    try await self.createPolicy(withPolling: withPolling, options: .init())
  }

  public func createPolicy(
    withPolling: CreatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createPolicy(
    parent: Swift.String,
    policy: Policy?,
    policyId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let request = CreatePolicyRequest().with {
      $0.parent = parent
      $0.policy = policy
      $0.policyId = policyId
    }
    return try await self.createPolicy(withPolling: request)
  }

  public func updatePolicy(request: UpdatePolicyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updatePolicy(request: request, options: .init())
  }

  public func updatePolicy(
    request: UpdatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updatePolicy(withPolling: UpdatePolicyRequest) async throws -> any GoogleGax
    .PollableOperation<Policy>
  {
    try await self.updatePolicy(withPolling: withPolling, options: .init())
  }

  public func updatePolicy(
    withPolling: UpdatePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deletePolicy(request: DeletePolicyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deletePolicy(request: request, options: .init())
  }

  public func deletePolicy(
    request: DeletePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deletePolicy(withPolling: DeletePolicyRequest) async throws -> any GoogleGax
    .PollableOperation<Policy>
  {
    try await self.deletePolicy(withPolling: withPolling, options: .init())
  }

  public func deletePolicy(
    withPolling: DeletePolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Policy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deletePolicy(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Policy> {
    let request = DeletePolicyRequest().with {
      $0.name = name
    }
    return try await self.deletePolicy(withPolling: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
